Regular Java io will not work on remote Jenkins slaves in Jenkins pipeline.
jenkinsci/contrast-continuous-application-security-plugin pull request #25
Opened 2018-06-20 15:30 UTC by ddooley77

Regular Java io will not work on remote Jenkins slaves.
The contrast.jar will not persist on the slave.
It is better to use the Hudson libraries

https://contrast.atlassian.net/browse/CONTRAST-24207

2018-06-20 16:17 UTC, gmoore commented
@serge17 Can you run this and shake out any problems?

2018-06-21 18:42 UTC, serge17 commented
@gmoore It runs OK.

2018-06-21 18:47 UTC, gmoore requested changes

2018-06-21 18:47 UTC, gmoore commented on src/main/java/com/aspectsecurity/contrast/contrastjenkins/ContrastAgentStep.java
> +            /* ddooley.  using FilePath instead of File.
@ddooley77 Can you strike this comment?

2018-06-27 03:29 UTC, ddooley77 commented on src/main/java/com/aspectsecurity/contrast/contrastjenkins/ContrastAgentStep.java
> +            /* ddooley.  using FilePath instead of File.
sure

2018-06-28 15:10 UTC, closed without merging